baseUrl: "https://wiredspace.de/"
languageCode: "en-us"
title: "wiredspace.de"
paginate: 1

menu:
    main:
        - name: Home
          identifier: home
          url: /
          weight: -100
        - name: Blog
          identifier: blog
          url: /blog/
          weight: -90
        - name: Wiki
          identifier: wiki
          url: /wiki/
          weight: -80
        - name: PrivateBin
          identifier: privatebin
          url: https://bin.wiredspace.de/
          weight: -70
        - name: About
          identifier: about
          url: /about/
          weight: -60
